[theme]
name = "plain"
[theme.overrides]
idle_bg = "#000817"
info_bg = "#000817"
separator_bg = "#000817"
good_bg = "#000817"
warning_bg = "#000817"
critical_bg = "#000817"
# alternating_tint_bg = "#000817"

[icons]
name = "awesome5"

[[block]]
block = "music"
hide_when_empty = true
on_click = "playerctl play-pause"
max_width = 50
dynamic_width = true

[[block]]
block = "cpu"

[[block]]
block = "temperature"
info = 65

[[block]]
block = "memory"
format_mem = "{Mup}%"
display_type = "memory"

[[block]]
block = "memory"
format_swap = "{SUp}%"
display_type = "swap"

# [[block]]
# block = "net"
# device = "wlp4s0"
# interval = 30

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "~/.config/i3status-rs/soundcard-name.sh"
# on_click = "/home/nomeji/.config/i3status-rs/soundcard-toggle.sh"
on_click = "~/.config/i3status-rs/soundcard-toggle.sh"

[[block]]
block = "time"
format = "%a %d %h %y | %H:%M"
interval = 60