[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#000817"
info_bg = "#000817"
separator_bg = "#000817"
good_bg = "#000817"
warning_bg = "#000817"
critical_bg = "#000817"
# alternating_tint_bg = "#000817"

[icons]
icons = "awesome6"

[[block]]
block = "music"
format = "{ $icon $combo.str(max_w:50,rot_interval:0.5) |}"
[[block.click]]
button = "left"
cmd = "playerctl play-pause"

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $average "
format_alt = " $icon $average avg, $max max "
info = 65

[[block]]
block = "memory"
format = " $icon $mem_used_percents $icon_swap $swap_used_percents "
format_alt = " $icon $mem_used.eng(w:3,u:B,p:M)/$mem_total.eng(w:3,u:B,p:M)($mem_used_percents.eng(w:2)) $icon_swap $swap_used.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "

[[block]]
block = "net"
device = "wlan0"
format_alt = " $icon $ssid$frequency \uf012 $signal_strength "

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "~/.config/i3status-rs/soundcard-name.sh"

[[block]]
block = "battery"

[[block]]
block = "time"
format = " ^icon_calendar $timestamp.datetime(f:'%a %d %h %y') $icon $timestamp.datetime(f:'%H:%M') "
interval = 1